l_spanish:
  train_body_decision_title:  "Es Hora de Entrenar"
  train_body_decision_desc: "Comenzar un riguroso entrenamiento físico para fortalecer cuerpo y espíritu."
  train_body_decision_confirm_text: "A entrenar"
  train_body_decision_selection_tooltip: "Es Hora de Sudar"